---
title: Cold Standby gibt "DataStoreException Record does not exists" aus
description: Beschreibung
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '311'
ht-degree: 0%

---

# Cold Standby gibt &quot;DataStoreException Record does not exists&quot; aus

## Beschreibung


<b>Problem:</b>
Cold Standby mit dedizierter Datei Datastore gibt eine Warnung zu fehlendem Blog aus, wie es bei 1 der Fall war.

<b>Details:</b>
Dies ist nur eine Warnung, kein Fehler. Es kommt aus der Tatsache, dass der Datenspeicher keine Möglichkeit hat, zu überprüfen, ob eine Binärdatei lokal vorhanden ist, außer durch den Versuch, Blob-ID zu laden.
Wenn die ID geladen wird, wird in den Protokollen diese Warnung nicht angezeigt. Wenn sie jedoch nicht gefunden wird, weiß die Standby, dass sie sie synchronisieren muss. Daher sehen wir die Warnung 1 in den Protokollen.


1: *\*WARN\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Fehler beim Laden von Bytes aus dem Dampf beim Abrufen der ID f68a92b34779bbd194184251ec9 16370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Datensatz f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a18 45 existiert nicht
<br>    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Verursacht durch: org.apache.jackrabbit.core.data.DataStoreException: Die Aufzeichnung &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20&quot;ist nicht vorhanden
<br>    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Auflösung


Dies funktioniert wie vorgesehen und zeigt kein Problem mit dem File DataStore an.

<b>So bestätigen Sie:</b>

- Beispiel-Blob-ID, die in den Protokollen als fehlend angezeigt wird: &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c 20&quot;
- Für diese Blob-ID sollte die Dateisystemadresse lauten: &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c4 9c20&quot;
- Durchsuchen Sie das Dateisystem auf der Standy-Instanz und überprüfen Sie, ob die benannte Datei im Datenspeicher vorhanden ist.
- Verwenden Sie in /repository/datastore den Befehl list (ls -ald): &quot;ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f193 5a2c49c20&quot;
- Sie sollten die Datei sehen und bestätigen können, dass die Blob-ID nicht fehlt.
