---
title: '"Cold Standby gibt den Fehler \"DataStoreException Record does not exists\" aus.'
description: Beschreibung
solution: Experience Manager
product: Experience Manager
applies-to: "Experience Manager"
keywords: "KCS, AEM, Cold Standby, DataStoreException, Adobe Experience Manager, Record not exists, error, warn, warning"
resolution: Resolution
internal-notes: "https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668"
bug: false
article-created-by: Jim Menn
article-created-date: "9/28/2022 2:23:47 PM"
article-published-by: Jim Menn
article-published-date: "9/28/2022 5:41:23 PM"
version-number: 3
article-number: KA-15610
dynamics-url: "https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad"
source-git-commit: dac4025ed5b544b848aba03a9e833d8fdffb6e88
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# Cold Standby gibt den Fehler &quot;DataStoreException Record not exists&quot;aus

## Beschreibung


<b>Umgebung</b>
Adobe Experience Manager

<b>Problem</b>
Cold Standby mit dediziertem File Datastore gibt eine Warnung bei fehlender Blob-ID aus, ähnlich dem Fehler hier:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Ursache</b>
Dies ist nur eine Warnung, kein Fehler.

Es kommt aus der Tatsache, dass der Dateidatenspeicher keine Möglichkeit hat, zu überprüfen, ob eine Binärdatei lokal vorhanden ist, außer durch den Versuch, die Blob-ID zu laden.
Wenn die ID geladen wird, wird in den Protokollen diese Warnung nicht angezeigt.
Wenn sie jedoch nicht gefunden wird, weiß die Standby, dass sie sie synchronisieren muss. Daher sehen Sie diese Art von Warnung in den Protokollen.


## Auflösung


<b>Lösung</b>
Dies funktioniert wie vorgesehen und zeigt kein Problem mit dem Dateidatenspeicher an.

Gehen Sie wie folgt vor, um zu bestätigen, dass die Blob-ID nicht fehlt:

1. Nehmen Sie beispielsweise Ihre Beispiel-Blob-ID, die in den Protokollen als fehlend angezeigt wird (z. B.: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Für diese Blob-ID in diesem Beispiel sollte die Dateisystemadresse wie folgt lauten: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Durchsuchen Sie das Dateisystem auf der Standby-Instanz und überprüfen Sie, ob die benannte Datei im Dateidatenspeicher vorhanden ist.
4. Within `/repository/datastore`, verwenden Sie die `list` (Beispiel: `ls -ald`), Befehl: `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Sie sollten die Datei sehen und bestätigen können, dass die Blob-ID nicht fehlt.

